version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: my-app
    command: "bash ./runapp.sh"
    environment:
    - CONNECTION_STRING
  db:
    image: postgres
    container_name: postgres
    restart: always
    expose:
      - "5432"
